# Generated by Django 5.2.5 on 2025-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_school_student',
            field=models.BooleanField(default=False),
        ),
    ]
