# Generated by Django 5.2.5 on 2025-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studnetsreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
